version: '2'
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
       - "5006:5006"
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432
      RUST_BACKTRACE: 1
      RUST_LOG: microservice=debug
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
